import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* Your custom script */}
        <Script id="redirect-handler" strategy="beforeInteractive">
          {`
            (function (l) {
              if (l.search[1] === "/") {
                var decoded = l.search
                  .slice(1)
                  .split("&")
                  .map(function (s) {
                    return s.replace(/~and~/g, "&");
                  })
                  .join("?");
                window.history.replaceState(
                  null,
                  null,
                  l.pathname.slice(0, -1) + decoded + l.hash
                );
              }
            })(window.location);
          `}
        </Script>
      </body>
    </html>
  );
}
